<a href="https://colab.research.google.com/github/Magdyibrahim112/Evently_cycle16/blob/development/assigment_sheet3_ml_magdy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(1)

In [11]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd

# Load the dataset
data = load_breast_cancer()
X = data.data  # Features
y = data.target  # Target (0 = malignant, 1 = benign)
print(data)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train logistic regression model
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(model.predict_proba(X_test[:5]))


accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("Confusion Matrix:")
print(cm)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


(2)

In [2]:
from sklearn.metrics import classification_report

# Calculate evaluation metrics
tn, fp, fn, tp = cm.ravel()

precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * (precision * recall) / (precision + recall)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

# Using sklearn's built-in function
print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Malignant', 'Benign']))

Precision: 0.9459
Recall: 0.9859
F1-Score: 0.9655

Detailed Classification Report:
              precision    recall  f1-score   support

   Malignant       0.97      0.91      0.94        43
      Benign       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



(3)

In [4]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd
# Load iris dataset
iris = load_iris()
X_iris = iris.data
y_iris = iris.target

# Split the data
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(
    X_iris, y_iris, test_size=0.3, random_state=42
)

# Create multi-class logistic regression model
# multi_class='multinomial' enables Softmax for multi-class classification
model_iris = LogisticRegression(multi_class='multinomial', random_state=42)
model_iris.fit(X_train_iris, y_train_iris)

# Predictions
y_pred_iris = model_iris.predict(X_test_iris)

# Evaluate
accuracy_iris = accuracy_score(y_test_iris, y_pred_iris)
cm_iris = confusion_matrix(y_test_iris, y_pred_iris)

print(f"Iris Dataset Accuracy: {accuracy_iris:.4f}")
print("Iris Confusion Matrix:")
print(cm_iris)
print(f"Class names: {iris.target_names}")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


Iris Dataset Accuracy: 1.0000
Iris Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Class names: ['setosa' 'versicolor' 'virginica']


(4)

In [5]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Create sample data with different scales
np.random.seed(42)
X_uneven = np.column_stack([
    np.random.normal(100, 10, 100),  # Large scale (mean=100)
    np.random.normal(0, 1, 100)      # Small scale (mean=0)
])
y_uneven = (X_uneven[:, 0] + X_uneven[:, 1] > 100).astype(int)

# Split data
X_train_u, X_test_u, y_train_u, y_test_u = train_test_split(
    X_uneven, y_uneven, test_size=0.3, random_state=42
)

# Model without scaling
model_no_scale = LogisticRegression(random_state=42)
model_no_scale.fit(X_train_u, y_train_u)
accuracy_no_scale = accuracy_score(y_test_u, model_no_scale.predict(X_test_u))

# Model with scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_u)
X_test_scaled = scaler.transform(X_test_u)

model_scaled = LogisticRegression(random_state=42)
model_scaled.fit(X_train_scaled, y_train_u)
accuracy_scaled = accuracy_score(y_test_u, model_scaled.predict(X_test_scaled))

print(f"Accuracy without scaling: {accuracy_no_scale:.4f}")
print(f"Accuracy with scaling: {accuracy_scaled:.4f}")
print(f"Improvement: {accuracy_scaled - accuracy_no_scale:.4f}")

Accuracy without scaling: 0.9667
Accuracy with scaling: 1.0000
Improvement: 0.0333


(5)

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score

#predict probabilities for positive class
proba = pipeline.predict_proba(X_test)[:, 1]

# Try different classification thresholds
thresholds = [0.3, 0.5, 0.7]

for t in thresholds:
    #convert probability to class label based on threshold
    preds = (proba >= t).astype(int)

    #evaluation metrics
    cm = confusion_matrix(y_test, preds)
    acc = accuracy_score(y_test, preds)

    print(f"\nThreshold = {t}")
    print("Confusion Matrix:")
    print(cm)
    print(f"Accuracy: {acc:.4f}")




Threshold = 0.3
Confusion Matrix:
[[52  2]
 [ 1 88]]
Accuracy: 0.9790

Threshold = 0.5
Confusion Matrix:
[[53  1]
 [ 2 87]]
Accuracy: 0.9790

Threshold = 0.7
Confusion Matrix:
[[53  1]
 [ 4 85]]
Accuracy: 0.9650


**Assignments**

(1)

In [21]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

#create pipeline: Standardization + Logistic Regression
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=5000))
])

#train the model
pipeline.fit(X_train, y_train)

accuracy = pipeline.score(X_test, y_test)

print(f"Pipeline Model Accuracy: {accuracy:.4f}")


Pipeline Model Accuracy: 0.9790


*We load the Breast Cancer dataset which contains numerical medical measurements.

*We split the data into training and test subsets.

*We build a Pipeline that applies:

1-StandardScaler: normalizes all features so they have zero mean and unit variance.

2-LogisticRegression: the classifier.

*The pipeline ensures that preprocessing happens inside the training process, preventing data leakage.

*.score() calculates accuracy on the test set.

(2)

In [20]:
import numpy as np

coeffs = np.abs(pipeline.named_steps['model'].coef_[0])
features = data.feature_names
top10 = sorted(zip(features, coeffs), key=lambda x: x[1], reverse=True)[:10]

print("Top 10 Features:")
for f, v in top10:
    print(f"{f}: {v:.4f}")


Top 10 Features:
worst texture: 1.3023
radius error: 1.2865
worst symmetry: 1.2267
mean concave points: 1.0880
worst concavity: 1.0064
area error: 0.8951
worst radius: 0.8463
worst area: 0.8223
worst concave points: 0.7752
mean concavity: 0.7355


*Get trained model: pipeline.named_steps['model'] retrieves the logistic regression trained in Q1.

*Coefficients: .coef_[0] gives the learned weights for each feature.

*Absolute value: abs() is used because a large negative coefficient is as important as a positive one.

*Pair & sort: combine feature names with their importance, then sort descending.

*Top features: print the 10 most influential features that contribute most to classification